'use strict';
const C=RecipeCore,E=C.escapeHtml;
const recipes=[...(window.RECIPE_DATA||[])];
let active='all',k='',q='',current,serv=null,lastFocus;
const typeName={main:'主菜',side:'副菜',rice:'ごはん・麺',sweet:'スイーツ',drink:'ドリンク',sauce:'ソース'};
function readSaved(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:fallback;}catch{return fallback;}}
let favs=readSaved('kojiFavs',[]),recent=readSaved('kojiRecent',[]),shopping=readSaved('kojiShopping',[]),checked=readSaved('kojiShoppingChecked',[]);
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{showToast('この端末では保存できません。ブラウザの保存設定をご確認ください。');}}
function imageStyle(r){return /^assets\/recipes\/[a-z0-9-]+\.webp$/.test(r.image||'')?r.image:`assets/recipes/recipe-${r.id}.webp`;}
function visibleRecipes(){return recipes.filter(r=>(active==='all'||active==='fav'&&favs.includes(r.id)||active==='community'&&r.author&&!r.origin||active==='import'&&r.origin==='cookpad'||active==='koji'&&r.koji||active==='no'&&!r.koji||r.type===active)&&(!k||C.normalize(r.koji)===C.normalize(k))&&C.matches(r,q));}
function render(){const list=visibleRecipes();grid.innerHTML=list.map(r=>`<article class="card" tabindex="0" role="button" aria-label="${E(r.title)}" onclick="openRecipe(${r.id})" onkeydown="if((event.key==='Enter'||event.key===' ')&&event.target===this){event.preventDefault();openRecipe(${r.id})}"><div class="photo"><span class="imageLabel">AI生成イメージ</span><img loading="lazy" decoding="async" alt="${E(r.title)}" src="${imageStyle(r)}"><button class="fav" aria-label="${favs.includes(r.id)?'お気に入りから削除':'お気に入りに保存'}" aria-pressed="${favs.includes(r.id)}" onclick="event.stopPropagation();toggleFav(${r.id})">${favs.includes(r.id)?'♥':'♡'}</button></div><div class="cardbody"><div class="tags"><span class="tag ${!r.koji?'g':''}">${E(r.koji||'糀なし')}</span><span class="tag g">${E(typeName[r.type]||'レシピ')}</span>${r.author?'<span class="tag">'+(r.origin==='cookpad'?'小春日和レシピ':'みんなの投稿')+'</span>':''}</div><h3>${E(r.title)}</h3><div class="meta">${E(r.desc)}</div>${r.author?`<small class="meta">投稿：${E(r.author)}</small>`:''}</div></article>`).join('');empty.style.display=list.length?'none':'block';recipeCount.textContent=`${list.length}品 / 全${recipes.length}品`;document.querySelectorAll('.chip').forEach(b=>b.classList.toggle('on',!k&&b.dataset.f===active));}
function scrollRecipes(){document.querySelector('#recipeHeading').scrollIntoView({behavior:'smooth',block:'start'});}
function clearQuery(){q='';search.value='';navSearch.value='';}
function filter(value){active=value;k='';clearQuery();render();scrollRecipes();}
function setKoji(value){active='all';k=value;clearQuery();render();scrollRecipes();}
function searchNow(value){q=value.trim();search.value=value;navSearch.value=value;active='all';k='';render();}
function foodSearch(value){searchNow(value);scrollRecipes();}
function showFav(){active='fav';k='';clearQuery();render();scrollRecipes();}
function resetAll(){active='all';k='';clearQuery();render();scrollTo({top:0,behavior:'smooth'});}
function focusSearch(){search.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>search.focus(),200);}
function toggleFav(id){if(!recipes.some(r=>r.id===id))return;favs=favs.includes(id)?favs.filter(v=>v!==id):[...favs,id];save('kojiFavs',favs);render();updateDetailFav();}
function updateDetailFav(){const button=document.getElementById('detailFav');if(current&&button){button.textContent=favs.includes(current.id)?'♥ 保存済み':'♡ お気に入り';button.setAttribute('aria-pressed',String(favs.includes(current.id)));}}
function updateRecipeUrl(id){const url=new URL(location.href);if(id==null)url.searchParams.delete('recipe');else url.searchParams.set('recipe',String(id));history.replaceState(null,'',url.pathname+url.search+url.hash);}
function openRecipe(id){const found=recipes.find(r=>r.id===Number(id));if(!found){showToast('このレシピは見つかりませんでした。');return;}lastFocus=document.activeElement;current=found;recent=[found.id,...recent.filter(v=>v!==found.id)].slice(0,6);save('kojiRecent',recent);renderRecent();serv=null;detailImg.src=imageStyle(found);detailImg.alt=`${found.title}のAI生成イメージ`;detailTitle.textContent=found.title;document.getElementById('sourceAttribution').innerHTML=found.origin==='cookpad'?`出典：発酵カフェ小春日和／クックパッド（レシピID ${Number(found.cookpadId)}）${/^https:\/\/cookpad\.com\/jp\/recipes\/\d+$/.test(found.sourceUrl||'')?` <a href="${E(found.sourceUrl)}" target="_blank" rel="noopener noreferrer">元の公開レシピ</a>`:''}`:'';detailMeta.textContent=`元の分量：${found.serving}　${found.desc}${found.author?'　投稿：'+found.author:''}`;detailTags.innerHTML=`<span class="tag">${E(found.koji||'糀なし')}</span><span class="tag g">${E(typeName[found.type])}</span>`;steps.innerHTML=found.steps.map(t=>`<li>${E(t)}</li>`).join('');const notices=C.quantityAudit(found);sourceNotice.style.display=notices.length?'block':'none';sourceNotice.textContent=notices.join(' ');note.style.display=found.note?'block':'none';note.textContent=found.note||'';const info=C.servingInfo(found),choices=info.unit==='倍量'?[0.5,1,2]:[1,2,4];document.querySelector('.serv').innerHTML=`<button class="on" type="button" onclick="setServing(null,this)">元の分量</button>${choices.map(n=>`<button type="button" onclick="setServing(${n},this)">${n}${info.unit}</button>`).join('')}`;updateDetailFav();drawIng();modal.classList.add('on');document.body.style.overflow='hidden';updateRecipeUrl(found.id);document.getElementById('detailClose').focus();}
function setServing(value,button){serv=value;document.querySelectorAll('.serv button').forEach(b=>b.classList.toggle('on',b===button));drawIng();}
function ingredientRows(){return C.ingredientRows(current,serv);}
function drawIng(){const info=C.servingInfo(current);document.getElementById('portionLabel').textContent=serv==null?`元の分量：${current.serving}`:info.unit==='倍量'?`元の全量に対して${serv}倍`:`${serv}${info.unit}の材料${info.min!==info.max?'（元の人数幅から計算）':''}`;ingredients.innerHTML=ingredientRows().map(([name,quantity])=>`<tr><td>${E(name)}</td><td>${E(quantity)}</td></tr>`).join('');}
function closeModal(){if(!modal.classList.contains('on'))return;modal.classList.remove('on');if(!shoppingPanel.classList.contains('on'))document.body.style.overflow='';updateRecipeUrl(null);if(lastFocus?.focus)lastFocus.focus();}
function showToast(text){toast.textContent=text;toast.style.display='block';setTimeout(()=>toast.style.display='none',2600);}
function renderRecent(){const list=recent.map(id=>recipes.find(r=>r.id===id)).filter(Boolean);recentWrap.innerHTML=list.length?`<div class="heading"><h2>最近見たレシピ</h2></div><div class="recent">${list.map(r=>`<button class="recentCard" onclick="openRecipe(${r.id})"><b>${E(r.title)}</b><small>${E(r.koji||'糀なし')} ・ ${E(typeName[r.type])}</small></button>`).join('')}</div>`:'';}
function addToShopping(){if(!current)return;const info=C.servingInfo(current);const portion=serv==null?current.serving:`${serv}${info.unit}`;ingredientRows().forEach(([name,quantity])=>{const item=`${name}：${quantity}（${current.title}／${portion}）`;if(!shopping.includes(item))shopping.push(item);});save('kojiShopping',shopping);showToast('表示中の分量を買い物リストへ保存しました。');}
async function copyText(text){try{if(!navigator.clipboard)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(text);showToast('コピーしました。');return true;}catch{const box=document.getElementById('copyFallback');box.value=text;document.getElementById('copyPanel').hidden=false;box.focus();box.select();showToast('コピー欄の文章を長押し・選択してコピーしてください。');return false;}}
async function shareCurrent(){if(!current)return;const url=new URL(location.pathname,location.origin);url.searchParams.set('recipe',String(current.id));const data={title:current.title,text:`${current.title}｜糀Life`,url:url.href};try{if(navigator.share){await navigator.share(data);return;}}catch(error){if(error.name==='AbortError')return;}await copyText(`${data.text} ${data.url}`);}
function showShopping(){shoppingList.innerHTML=shopping.length?shopping.map((text,i)=>`<label class="shoppingItem"><input type="checkbox" ${checked.includes(text)?'checked':''} onchange="checkShopping(${i},this.checked)"><span>${E(text)}</span></label>`).join(''):'<p>まだ材料が保存されていません。</p>';shoppingPanel.classList.add('on');document.body.style.overflow='hidden';}
function checkShopping(index,isChecked){const item=shopping[index];checked=isChecked?[...new Set([...checked,item])]:checked.filter(v=>v!==item);save('kojiShoppingChecked',checked);}
function closeShopping(){shoppingPanel.classList.remove('on');if(!modal.classList.contains('on'))document.body.style.overflow='';}
function clearShopping(){if(!confirm('買い物リストをすべて削除しますか？'))return;shopping=[];checked=[];save('kojiShopping',shopping);save('kojiShoppingChecked',checked);showShopping();}
async function shareShopping(){const text='糀Life 買い物リスト\n'+shopping.map(item=>`${checked.includes(item)?'☑':'□'} ${item}`).join('\n');try{if(navigator.share){await navigator.share({title:'糀Life 買い物リスト',text});return;}}catch(error){if(error.name==='AbortError')return;}await copyText(text);}
document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>filter(b.dataset.f));document.querySelectorAll('.koji').forEach(b=>b.onclick=()=>setKoji(b.dataset.k));search.oninput=e=>searchNow(e.target.value);navSearch.oninput=e=>searchNow(e.target.value);search.onkeydown=e=>{if(e.key==='Enter'){searchNow(search.value);scrollRecipes();}};navSearch.onkeydown=e=>{if(e.key==='Enter'){searchNow(navSearch.value);scrollRecipes();}};
shoppingPanel.onclick=e=>{if(e.target===shoppingPanel)closeShopping();};modal.onclick=e=>{if(e.target===modal)closeModal();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(shoppingPanel.classList.contains('on'))closeShopping();else closeModal();}if(e.key==='Tab'&&modal.classList.contains('on')){const buttons=[...modal.querySelectorAll('button,a,input,textarea')].filter(n=>!n.disabled);const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
const sharedId=Number(new URLSearchParams(location.search).get('recipe'));renderRecent();render();if(sharedId&&recipes.some(r=>r.id===sharedId))openRecipe(sharedId);
async function loadCommunity(){try{const response=await fetch('./community-recipes.json',{cache:'no-cache'});if(!response.ok)throw new Error('Post data unavailable');const list=await response.json();if(!Array.isArray(list))throw new Error('Invalid post data');for(const r of list){if(!Number.isInteger(r.id)||r.id<200000||recipes.some(v=>v.id===r.id)||C.validateSubmission({...r,schema:'koji-life-submission-v1',consent:true}).length||!/^assets\/recipes\/post-\d+\.webp$/.test(r.image||''))continue;recipes.push(r);}renderRecent();render();if(sharedId&&!current&&recipes.some(r=>r.id===sharedId))openRecipe(sharedId);else if(sharedId&&!recipes.some(r=>r.id===sharedId)){showToast('リンク先のレシピは見つかりませんでした。');updateRecipeUrl(null);}}catch{document.getElementById('communityNotice').textContent='投稿レシピの読み込みに失敗しました。再読み込みでお試しください。';}}
loadCommunity();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
