(function(root){'use strict';let client,settings;const VERSION='2026-10-07';const PREFS='北海道 青森県 岩手県 宮城県 秋田県 山形県 福島県 茨城県 栃木県 群馬県 埼玉県 千葉県 東京都 神奈川県 新潟県 富山県 石川県 福井県 山梨県 長野県 岐阜県 静岡県 愛知県 三重県 滋賀県 京都府 大阪府 兵庫県 奈良県 和歌山県 鳥取県 島根県 岡山県 広島県 山口県 徳島県 香川県 愛媛県 高知県 福岡県 佐賀県 長崎県 熊本県 大分県 宮崎県 鹿児島県 沖縄県'.split(' ');
const LABELS={name:'食品の名称',ingredients:'原材料名（重量順）',additives:'添加物（使用なしも明記）',origin:'原料原産地名',allergens:'アレルゲン（対象なしも明記）',content:'内容量',expiry:'賞味期限／消費期限の案内',storage:'保存方法・開封後の扱い',manufacturer:'製造者／加工者の氏名・名称',manufacturer_address:'製造所／加工所の所在地',nutrition:'栄養成分表示・単位（免除の場合は根拠）',temperature:'配送温度帯'};
function validateConfig(c){try{const u=new URL(c.supabaseUrl);return /^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(u.origin)&&u.href===u.origin+'/'&&typeof c.supabasePublishableKey==='string'&&(c.supabasePublishableKey.startsWith('sb_publishable_')||(!c.supabasePublishableKey.startsWith('sb_secret_')&&JSON.parse(atob(c.supabasePublishableKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role==='anon'));}catch{return false;}}
function unwrap(r){if(r.error)throw r.error;return r.data;}
async function init(){if(settings)return settings;const r=await fetch('member-config.json',{cache:'no-store'});if(!r.ok)throw Error('会員機能の設定を読み込めません。');settings=await r.json();if(validateConfig(settings)&&root.supabase){const storage={getItem:k=>localStorage.getItem('koji-remember-session')==='yes'?localStorage.getItem(k):sessionStorage.getItem(k),setItem:(k,v)=>{(localStorage.getItem('koji-remember-session')==='yes'?localStorage:sessionStorage).setItem(k,v);},removeItem:k=>{localStorage.removeItem(k);sessionStorage.removeItem(k);}};client=root.supabase.createClient(settings.supabaseUrl,settings.supabasePublishableKey,{auth:{storage,storageKey:'koji-member-auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});}return settings;}
async function requireClient(){await init();if(!client)throw Error('会員登録は接続準備中です。個人情報の受付はまだ開始していません。');return client;}
async function user(){await init();if(!client)return null;const r=await client.auth.getUser();if(r.error){const s=await client.auth.getSession();if(!s.data.session)return null;throw r.error;}return r.data.user;}
async function sendCode(email,remember){const c=await requireClient();if(!settings.emailDeliveryReady)throw Error('メール認証の配信設定を準備中です。');localStorage.setItem('koji-remember-session',remember?'yes':'no');unwrap(await c.auth.signInWithOtp({email,options:{shouldCreateUser:true}}));}
async function verify(email,token){const c=await requireClient();return unwrap(await c.auth.verifyOtp({email,token,type:'email'}));}
async function signOut(){const c=await requireClient();unwrap(await c.auth.signOut());}
async function profile(){const u=await user();if(!u)return null;return unwrap(await client.from('koji_profiles').select('*').eq('user_id',u.id).maybeSingle());}
async function saveProfile(v){const c=await requireClient();return unwrap(await c.rpc('koji_save_profile',{p_name:v.name,p_recipient:v.recipient,p_postal:v.postal_code.replace(/[^0-9]/g,''),p_prefecture:v.prefecture,p_address:v.address,p_phone:v.phone.replace(/[^0-9]/g,''),p_marketing:!!v.marketing_opt_in,p_privacy_version:VERSION}));}
async function catalog(){await init();if(!client){const r=await fetch('shop-config.json',{cache:'no-store'});if(!r.ok)throw Error('商品情報を取得できません。');return r.json();}const [p,s]=await Promise.all([client.from('koji_products').select('*').order('sort_order'),client.from('koji_settings').select('*').eq('id',1).single()]);const products=unwrap(p).map(p=>({...p,externalUrl:p.external_url}));const cfg=unwrap(s);return {products,shippingFee:cfg.shipping_fee,ordersEnabled:cfg.orders_enabled&&cfg.bank_enabled&&!!settings.ordersReady};}
async function orders(){const c=await requireClient();return unwrap(await c.from('koji_orders').select('*,koji_order_items(*)').order('created_at',{ascending:false}).limit(100));}
async function placeOrder(items,key,total){const c=await requireClient();if(!settings.ordersReady)throw Error('注文受付は準備中です。');return unwrap(await c.rpc('koji_place_order',{p_items:items,p_request_key:key,p_terms_version:VERSION,p_expected_total:total}));}
async function isAdmin(){await init();return client?!!unwrap(await client.rpc('koji_is_admin')):false;}
async function updateProduct(id,v){const c=await requireClient();return unwrap(await c.from('koji_products').update(v).eq('id',id).select().single());}
async function allProducts(){const c=await requireClient();return unwrap(await c.from('koji_products').select('*').order('sort_order'));}
async function setOrders(enabled){const c=await requireClient();return unwrap(await c.from('koji_settings').update({orders_enabled:enabled,bank_enabled:enabled}).eq('id',1).select().single());}
async function orderState(id,status,tracking){const c=await requireClient();return unwrap(await c.rpc('koji_admin_order',{p_order_id:id,p_status:status,p_tracking:tracking||''}));}
function labelRows(p,products){if(p.food_kind==='nonfood')return [];if(!p.label_confirmed)return [['食品表示','確認中です。確認が完了するまで注文はできません。']];if(p.food_kind==='set'){const ids=p.food_label?.components||[];return ids.flatMap(id=>{const item=products.find(p=>p.id===id);return item&&item.food_kind==='food'?[['セット内容',item.name],...labelRows(item,products)]:[['セット内容','確認中']];});}return Object.entries(LABELS).map(([key,label])=>[label,p.food_label?.[key]||'確認中']);}
root.MemberAPI={init,user,sendCode,verify,signOut,profile,saveProfile,catalog,orders,placeOrder,isAdmin,updateProduct,allProducts,setOrders,orderState,labelRows,LABELS,PREFS,VERSION,validateConfig};if(typeof module!=='undefined')module.exports=root.MemberAPI;
})(globalThis);
