'use strict';
const ids=['title','author','desc','type','koji','base','unit','ingredients','instructions','imageMode'];let submissionJson='',objectUrl;
function value(id){return document.getElementById(id).value.trim();}
function buildSubmission(){return {imageMode:value('imageMode'),schema:'koji-life-submission-v1',title:value('title'),author:value('author'),desc:value('desc'),type:value('type'),koji:value('koji'),base:value('unit')==='倍量'?1:Number(value('base')),servingUnit:value('unit'),ing:value('ingredients').split(/\r?\n/).map(line=>line.trim().replace(/\s*[:：]\s*/, '：')).filter(Boolean),steps:value('instructions').split(/\r?\n/).map(line=>line.trim().replace(/^\d+[.．、)）]\s*/, '')).filter(Boolean),consent:document.getElementById('consent').checked};}
function saveDraft(){try{const draft={};for(const id of ids)draft[id]=document.getElementById(id).value;localStorage.setItem('kojiPostDraft',JSON.stringify(draft));draftStatus.textContent='下書きをこの端末に保存しました。';}catch{draftStatus.textContent='この端末では下書きを保存できません。';}}
try{const draft=JSON.parse(localStorage.getItem('kojiPostDraft')||'null');if(draft)for(const id of ids)if(typeof draft[id]==='string')document.getElementById(id).value=draft[id];}catch{}
postForm.onsubmit=async event=>{event.preventDefault();const data=buildSubmission(),errors=RecipeCore.validateSubmission(data);if(errors.length){formError.textContent=errors.join('\n');return;}formError.textContent='';if(data.imageMode==='photo'){try{data.photoData=await encodePhoto();}catch(e){formError.textContent=e.message;return;}}submissionJson=JSON.stringify(data,null,2);submissionText.value=submissionJson;preview.textContent=`${data.title}\n投稿：${data.author}\n${data.base}${data.servingUnit}\n\n材料\n${data.ing.join('\n')}\n\n作り方\n${data.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}`;const file=`submissions/recipe-${Date.now()}.json`,url=new URL('https://github.com/heart1650-byte/koji-life/new/main');url.searchParams.set('filename',file);url.searchParams.set('message',`[糀Life投稿] ${data.title}`);url.searchParams.set('value',submissionJson);if(url.href.length>7000){url.searchParams.delete('value');copyStatus.textContent='長いレシピのため、投稿データをコピーしてGitHubの入力欄へ貼り付けてください。';}else copyStatus.textContent='';submitLink.href=url.href;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(new Blob([submissionJson],{type:'application/json'}));downloadLink.href=objectUrl;downloadLink.download=file.split('/').pop();result.hidden=false;result.scrollIntoView({behavior:'smooth'});saveDraft();};
async function copySubmission(){try{await navigator.clipboard.writeText(submissionJson);copyStatus.textContent='投稿データをコピーしました。';}catch{submissionText.parentElement.open=true;submissionText.focus();submissionText.select();copyStatus.textContent='投稿データを選択しました。コピーして貼り付けてください。';}}

const photoInput=document.getElementById('recipePhoto'),photoPreview=document.getElementById('photoPreview');let photoPreviewUrl;
function syncPhotoMode(){document.getElementById('photoFields').hidden=value('imageMode')!=='photo';}
document.getElementById('imageMode').addEventListener('change',syncPhotoMode);syncPhotoMode();
photoInput.addEventListener('change',()=>{if(photoPreviewUrl)URL.revokeObjectURL(photoPreviewUrl);photoPreview.hidden=!photoInput.files.length;if(photoInput.files.length){photoPreviewUrl=URL.createObjectURL(photoInput.files[0]);photoPreview.src=photoPreviewUrl;}});
async function encodePhoto(){const file=photoInput.files[0];if(!file)throw Error('掲載する料理写真を選んでください。');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('JPEG・PNG・WebPの10MB以下の画像を選んでください。');const image=new Image(),url=URL.createObjectURL(file);try{image.src=url;await image.decode();const ratio=Math.min(1,960/Math.max(image.width,image.height)),c=document.createElement('canvas');c.width=Math.round(image.width*ratio);c.height=Math.round(image.height*ratio);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(image,0,0,c.width,c.height);const data=c.toDataURL('image/webp',0.75);if(!data.startsWith('data:image/webp;base64,')||data.length>700000)throw Error('画像を保存できません。小さい写真を選ぶか、別のブラウザで試してください。');return data;}catch(e){throw Error(e.message||'この写真を読み込めませんでした。');}finally{URL.revokeObjectURL(url);}}
