(function(root){
  'use strict';
  const aliases=[[/糀|麹/g,'こうじ'],[/醤こうじ|しょうゆこうじ/g,'醤油こうじ'],[/納豆こうじ/g,'納豆こうじ'],[/しょうが|ショウガ|生姜/g,'しょうが'],[/じゃがいも|ジャガイモ|馬鈴薯/g,'じゃがいも'],[/さつまいも|サツマイモ|サツマイモ|薩摩芋/g,'さつまいも'],[/にんじん|ニンジン|人参/g,'にんじん'],[/かぶ|カブ|蕪/g,'かぶ'],[/くるみ|クルミ|胡桃/g,'くるみ'],[/エビ|海老|えび/g,'えび'],[/鶏肉|とり肉|とりにく|チキン/g,'鶏'],[/ご飯|ごはん/g,'ごはん']];
  function normalize(text){let value=String(text||'').normalize('NFKC').toLowerCase();for(const [pattern,replacement] of aliases)value=value.replace(pattern,replacement);return value.replace(/\s+/g,' ').trim();}
  function matches(recipe,query){const haystack=normalize([recipe.title,recipe.desc,recipe.koji,...recipe.ing].join(' '));return normalize(query).split(/[\s　]+/).filter(Boolean).every(term=>haystack.includes(term));}
  function escapeHtml(text){return String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function numberValue(token){const parts=token.trim().split(/\s+/);const fraction=parts.pop();if(fraction.includes('/')){const [a,b]=fraction.split('/').map(Number);return (parts.length?Number(parts[0]):0)+a/b;}return Number(fraction);}
  function formatNumber(value){if(!Number.isFinite(value))return '';const rounded=Math.round(value*1000)/1000;if(Math.abs(rounded-Math.round(rounded))<0.00001)return String(Math.round(rounded));for(const d of [2,3,4,6,8,12]){const numerator=Math.round(value*d);if(Math.abs(value-numerator/d)<0.000001){const whole=Math.floor(numerator/d),rem=numerator%d;return whole?(rem?`${whole}と${rem}/${d}`:String(whole)):`${rem}/${d}`;}}return String(rounded);}
  const NUMBER='(?:\\d+\\s+\\d+\\/\\d+|\\d+\\/\\d+|\\d+(?:\\.\\d+)?)';
  function scaleQuantity(value,ratio){if(ratio===1)return String(value);return String(value).replace(new RegExp(NUMBER,'g'),token=>formatNumber(numberValue(token)*ratio));}
  function scaleRangeQuantity(value,minRatio,maxRatio){if(minRatio===maxRatio)return scaleQuantity(value,minRatio);return String(value).replace(new RegExp(`(${NUMBER})(?:\\s*[〜～~–－-]\\s*(${NUMBER}))?`,'g'),(_,lo,hi)=>{const a=numberValue(lo)*minRatio,b=numberValue(hi||lo)*maxRatio;return `${formatNumber(a)}〜${formatNumber(b)}`;});}
  function servingInfo(r){const text=r.serving||'';if(r.servingUnit==='倍量')return {unit:'倍量',min:1,max:1};if(r.servingUnit&&Number.isFinite(r.base)&&r.base>0)return {unit:r.servingUnit,min:r.base,max:r.base};const range=text.match(/(\d+)\s*[〜～]\s*(\d+)人分/);if(range)return {unit:'人分',min:Number(range[1]),max:Number(range[2])};const people=text.match(/(\d+)人分/);if(people)return {unit:'人分',min:Number(people[1]),max:Number(people[1])};if(/杯分/.test(text))return {unit:'杯分',min:r.base,max:r.base};if(/本分/.test(text)&&!/人分/.test(text))return {unit:'本分',min:r.base,max:r.base};if(/個分/.test(text)&&!/人分/.test(text))return {unit:'個分',min:r.base,max:r.base};if(/米\d+合分/.test(text))return {unit:'合分',min:r.base,max:r.base};return {unit:'倍量',min:1,max:1};}
  function ingredientRows(r,target){const info=servingInfo(r);const original=target==null;const minRatio=original?1:target/info.max,maxRatio=original?1:target/info.min;return r.ing.map(item=>{const separator=item.indexOf('：');const name=separator<0?item:item.slice(0,separator);const quantity=separator<0?'分量未確認':item.slice(separator+1);return [name,original?quantity:scaleRangeQuantity(quantity,minRatio,maxRatio)];});}
  function quantityAudit(r){const info=servingInfo(r),issues=[];if(r.ing.some(v=>/記載なし|未確認/.test(v)))issues.push('元資料に分量がない材料があります。量は要確認です。');if(info.unit==='倍量')issues.push('元資料に人数・個数の記載がありません。人数は断定せず、全量に対する倍率で調整します。');if(info.min!==info.max)issues.push(`元資料は${info.min}〜${info.max}人分です。人数変更時はこの幅を反映した分量の範囲を表示します。`);if(r.auditNote)issues.push(r.auditNote);return issues;}
  function validateSubmission(input){const errors=[];if(!input||input.schema!=='koji-life-submission-v1')return ['投稿データの形式が違います。'];for(const [field,max] of [['title',80],['author',40],['desc',240],['koji',40]]){if(typeof input[field]!=='string'||input[field].length>max)errors.push(`${field}を確認してください。`);}if(!input.title?.trim()||!input.author?.trim())errors.push('料理名と投稿者名が必要です。');if(!['main','side','rice','sweet','drink','sauce'].includes(input.type))errors.push('料理の分類が必要です。');if(!['人分','個分','杯分','本分','倍量'].includes(input.servingUnit)||!Number.isFinite(input.base)||input.base<=0||input.base>100)errors.push('人数・個数を確認してください。');if(!Array.isArray(input.ing)||input.ing.length<1||input.ing.length>30||input.ing.some(x=>typeof x!=='string'||x.length>160||!x.includes('：')||!x.split('：')[0].trim()||!x.slice(x.indexOf('：')+1).trim()||/\d+\s*\/\s*0(?:\D|$)/.test(x)))errors.push('材料を「材料名：分量」で入力してください。');if(!Array.isArray(input.steps)||input.steps.length<1||input.steps.length>20||input.steps.some(x=>typeof x!=='string'||!x.trim()||x.length>400))errors.push('作り方を1〜20行で入力してください。');if(input.consent!==true)errors.push('投稿内容の公開への同意が必要です。');return errors;}
  const api={normalize,matches,escapeHtml,numberValue,formatNumber,scaleQuantity,servingInfo,ingredientRows,quantityAudit,validateSubmission};root.RecipeCore=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
